server:
    port: 8080

master:
    datasource:
        # 数据库连接地址
        url: jdbc:mysql://139.199.206.114:3308/imovie?useUnicode=true&characterEncoding=utf-8&useSSL=false
        # MySQL驱动
        driverClassName: com.mysql.jdbc.Driver
        # 数据库账号
        username: root
        # 数据库密码
        password: Hidl8991*9102#@9
        # druid连接池
        type: com.alibaba.druid.pool.DruidDataSource

second:
    datasource:
        # 数据库连接地址
        url: jdbc:mysql://localhost:3306/keeko?useUnicode=true&characterEncoding=utf-8&useSSL=false
        # MySQL驱动
        driverClassName: com.mysql.jdbc.Driver
        # 数据库账号
        username: root
        # 数据库密码
        password: 123456
        # druid连接池
        type: com.alibaba.druid.pool.DruidDataSource

